version: 0.0
os: linux
files:
  - source: dist/build/yesod-website/yesod-website
    destination: /opt/yesod-website
hooks:
  ApplicationStop:
    - location: scripts/codedeploy_appstop.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy_appstart.sh
      timeout: 5
      runas: root
