version: 0.0
os: linux
files:
  - source: dist/build/yesod-website/yesod-website
    destination: /opt/yesod-website
hooks:
  ApplicationStart:
    - location: scripts/launch_with_codedeploy.sh
      timeout: 5
      runas: root
