version: 0.0
os: linux
files:
  - source: dist/build/yesod-website/yesod-website
    destination: /opt/yesod-website
hooks:
  ApplicationStart:
    - location: /opt/yesod-website/yesod-website
      timeout: 5
      runas: root
